'use client';
import {useState} from 'react';
import {Play,RotateCcw,Check} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Range,Choice,Stats,Stat,Note,Finding,Formula,Bars,LinePlot,LabProps} from './shared';
import {softmax,topP,sample,fmt,entropy,tinyVocab,tinyLoss,tinyStep} from '@/lib/academy/math';
export function InferenceLab({onComplete}:LabProps){
 const [temp,setTemp]=useState(1),[threshold,setThreshold]=useState(.95),[cache,setCache]=useState(false),[counts,setCounts]=useState<number[]|null>(null),[sampleParams,setSampleParams]=useState(''),[low,setLow]=useState(false),[high,setHigh]=useState(false),[context,setContext]=useState(1024),[rag,setRag]=useState(false);
 const labels=['地毯','椅子','沙发','桌面','月亮','代码'],raw=softmax([2.5,1.8,1.3,.6,-.8,-1.4],temp),p=topP(raw,threshold),kv=2*32*context*8*128*2/2**20;
 function draw(){const c=labels.map(()=>0);for(let i=0;i<100;i++)c[sample(p,Math.random())]++;setCounts(c.map(n=>n/100));setSampleParams(`T=${fmt(temp,1)}，top-p=${fmt(threshold,2)}`);setLow(low||temp<=.5);setHigh(high||temp>=1.5);}
 const ok=low&&high&&cache;
 return <><div className="stage"><div className="stage-label">采样分布 / 输入：小猫坐在</div><Bars labels={labels} values={p}/><div className="plot-legend"><span><i style={{background:'#74e8bd'}}/>当前设置的理论概率</span></div>{counts&&<div className="sample-result"><div className="section-label">上一轮 100 次独立采样 · {sampleParams}</div><Bars labels={labels} values={counts} color="#829ffa"/></div>}</div><div className="two-controls"><Range label="温度 T" value={temp} set={setTemp} min={.2} max={2} step={.1} digits={1}/><Range label="top-p 阈值" value={threshold} set={setThreshold} min={.1} max={1} step={.05}/></div><button className="btn primary" onClick={draw}><Play size={16}/>采样 100 次</button><div className="experiment-checks"><span className={low?'complete':''}>{low?'✓':'○'} 低温采样</span><span className={high?'complete':''}>{high?'✓':'○'} 高温采样</span><span className={cache?'complete':''}>{cache?'✓':'○'} KV 缓存</span></div><div className="kv-section"><label className="switch-label"><Switch checked={cache} onCheckedChange={setCache} aria-label="KV 缓存"/>启用 KV 缓存</label><Range label="已有上下文长度" value={context} set={setContext} min={256} max={8192} step={256} digits={0}/><Stats><Stat label="本轮需重新计算 K/V 的位置" value={cache?1:context+1}/><Stat label="历史 KV 占用估算" value={cache?fmt(kv,1):'0'} unit=" MiB"/><Stat label="当前分布熵" value={fmt(entropy(p))} unit=" nats"/></Stats></div><button className="btn primary" disabled={!ok} onClick={()=>onComplete('完成高低温采样比较，并观察 KV 缓存如何用显存换取历史计算复用。')}>记录推理实验</button><details className="lab-details"><summary>资料变了，需要重新训练吗？</summary><label className="switch-label"><Switch checked={rag} onCheckedChange={setRag} aria-label="加入检索资料"/>加入一条检索资料</label><div className="retrieval"><strong>问题：工坊的实验室几点关闭？</strong>{rag?<><p>检索片段：「模型工坊实验室开放至 21:00。」</p><p>有依据的回答：根据提供的开放时间，实验室于 21:00 关闭。</p></>:<p>上下文没有开放时间。有依据的回答应说明缺少信息，并请求可靠来源。</p>}</div><p>这是一个固定情景对照，展示 RAG 改变输入依据的方式。没有调用大模型，也没有更新模型权重。</p></details><Note>KV 估算假设 32 层、8 个 KV 头、每头 128 维、BF16，batch=1。它不包含权重或其他中间状态。缓存仍需读取历史 K/V，不代表整次生成变成常数时间。</Note></>;
}
const initWeights=()=>Array.from({length:8},()=>Array(8).fill(0) as number[]);
export function EvaluationLab({onComplete}:LabProps){
 const [w,setW]=useState(initWeights),[steps,setSteps]=useState(0),[history,setHistory]=useState([Math.log(8)]),[context,setContext]=useState('0'),[evaluated,setEvaluated]=useState(false),[leak,setLeak]=useState(false),[showData,setShowData]=useState(false);
 const last=context==='2'?3:2,p=softmax(w[last]);
 function train(n:number){let a=w.map(row=>[...row]);const h=[...history];for(let i=0;i<n;i++){a=tinyStep(a,3);h.push(tinyLoss(a));}setW(a);setHistory(h);setSteps(steps+n);setEvaluated(false);}
 function evaluate(){setEvaluated(true);if(steps>=50)onComplete('已训练 64 参数语言模型至少 50 步，并验证它无法利用更早的主语。');}
 return <><div className="stage"><div className="stage-label">可训练语言模型 / 8 个 token × 8 个 logits = 64 参数</div><div className="tiny-corpus"><span>小猫 喜欢 鱼 。</span><span>小狗 喜欢 骨头 。</span><span>小猫 坐在 地毯 。</span><span>小狗 坐在 地毯 。</span></div><LinePlot series={[history]} labels={['训练集平均交叉熵']}/></div><div className="actions"><button className="btn primary" onClick={()=>train(50)} disabled={steps>=500}><Play size={16}/>训练 50 步</button><button className="btn" onClick={()=>train(1)} disabled={steps>=500}>训练 1 步</button><button className="btn icon" aria-label="重置微型语言模型" onClick={()=>{setW(initWeights());setSteps(0);setHistory([Math.log(8)]);setEvaluated(false);}}><RotateCcw size={16}/></button></div><Stats><Stat label="实际训练步数" value={steps} unit=" / 500"/><Stat label="当前训练损失" value={fmt(tinyLoss(w),3)} unit=" nats"/><Stat label="可用上下文" value="最后 1 个 token"/></Stats><Choice label="观察下一词预测" value={context} set={setContext} options={[{value:'0',label:'小猫 喜欢 …'},{value:'1',label:'小狗 喜欢 …'},{value:'2',label:'小猫 坐在 …'}]}/><Bars labels={tinyVocab} values={p}/><div className="actions"><button className="btn primary" onClick={evaluate}>检查上下文区分能力</button><button className="btn" onClick={()=>setShowData(!showData)}>{showData?'收起参数表':'查看学习后的参数表'}</button></div>{evaluated&&<Finding success={steps>=50}><b>诊断：两个「喜欢」结尾的上下文，输出分布完全相同。</b><br/>“鱼”和“骨头”的概率都为 {fmt(softmax(w[2])[4]*100,1)}%。模型只读取最后一个 token，无法利用前面的主语。{steps<50?'先训练至少 50 步，再检查一次。':'损失下降了，但上下文能力仍受结构限制。'}</Finding>}{showData&&<div className="weight-table-wrap"><table className="weight-table"><caption>每行是输入 token，每列是下一 token 的 logit</caption><thead><tr><th>输入 / 输出</th>{tinyVocab.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{w.map((row,i)=><tr key={i}><th>{tinyVocab[i]}</th>{row.map((v,j)=><td key={j} style={{background:`rgba(116,232,189,${Math.min(.45,Math.max(0,v)*.09)})`}}>{fmt(v,1)}</td>)}</tr>)}</tbody></table></div>}<details className="lab-details"><summary>再做一次数据泄漏的对照实验</summary><p>下面使用固定的模拟评测结果：10 道未见题答对 6 道，10 道训练原题全部答对。比较把原题混入后的平均分。</p><label className="switch-label"><Switch checked={leak} onCheckedChange={setLeak} aria-label="混入训练原题"/>评测中混入 10 道训练原题</label><Stats><Stat label="报告中的准确率" value={leak?'80':'60'} unit="%"/><Stat label="真正未见题的准确率" value="60" unit="%"/><Stat label="评测样本数" value={leak?20:10}/></Stats><p>平均分变好，并不意味着泛化能力提高。真实验收还需覆盖任务子集、长尾、安全、延迟和成本。</p></details><Note>这个模型在你的浏览器中执行真实的交叉熵和梯度下降。它是 bigram 模型，不是 Transformer。无序列记忆、无外部服务；训练与测试数据都可见，便于追踪每个数值的来源。</Note></>;
}
