'use client';
import {useState} from 'react';
import {Play,RotateCcw,Check} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Range,Choice,Stats,Stat,Note,Finding,Formula,Bars,LinePlot,LabProps} from './shared';
import {softmax,fmt,optimizerStep,OptState,memoryEstimate,sigmoid,softplus} from '@/lib/academy/math';
export function LossLab({onComplete}:LabProps){
 const [z,setZ]=useState([1.8,.8,-.4,1.2]),[history,setHistory]=useState<number[]>([-Math.log(softmax([1.8,.8,-.4,1.2])[2])]),[lr,setLr]=useState(.5),[steps,setSteps]=useState(0);const p=softmax(z),g=p.map((v,i)=>v-(i===2?1:0));
 function step(){const next=z.map((v,i)=>v-lr*g[i]),np=softmax(next);setZ(next);setHistory([...history,-Math.log(np[2])]);setSteps(steps+1);if(np[2]>.8)onComplete(`经过 ${steps+1} 次 logit 更新，目标概率达到 ${fmt(np[2]*100,1)}%，损失为 ${fmt(-Math.log(np[2]),3)}。`);}
 return <><div className="stage"><div className="stage-label">输入：小猫坐在　目标：地毯</div><Bars labels={['椅子','月亮','地毯','代码']} values={p} highlight={2}/><div className="gradient-table"><div><span>候选 token</span><span>logit z</span><span>目标 y</span><span>梯度 p−y</span></div>{['椅子','月亮','地毯','代码'].map((s,i)=><div key={s} className={i===2?'target':''}><span>{s}</span><code>{fmt(z[i],3)}</code><code>{i===2?1:0}</code><code>{fmt(g[i],3)}</code></div>)}</div></div><div className="lab-controls"><Range label="分数更新步幅 η" value={lr} set={setLr} min={.1} max={1} step={.1} digits={1}/><div className="actions"><button className="btn primary" onClick={step}><Play size={16}/>更新一次</button><button className="btn icon" aria-label="重置交叉熵实验" onClick={()=>{const a=[1.8,.8,-.4,1.2];setZ(a);setHistory([-Math.log(softmax(a)[2])]);setSteps(0);}}><RotateCcw size={16}/></button></div></div><Stats><Stat label="目标概率" value={fmt(p[2]*100,1)} unit="%"/><Stat label="交叉熵 −ln p" value={fmt(-Math.log(p[2]),3)} unit=" nats"/><Stat label="更新次数" value={steps}/></Stats><LinePlot series={[history]}/><Formula>zᵢ ← zᵢ − {fmt(lr,1)} × (pᵢ − yᵢ)</Formula><Note>nats 是使用自然对数时的单位。这里把 logits 当成可直接训练的 4 个参数。真实 Transformer 的分数由各层参数计算，反馈还要沿计算路径传回这些参数，下一章会展开。</Note></>;
}
const initial:OptState={w:-4,m:0,v:0,t:0};
export function OptimizerLab({onComplete}:LabProps){
 const [state,setState]=useState(initial),[method,setMethod]=useState('SGD'),[lr,setLr]=useState(.2),[history,setHistory]=useState([49]),[error,setError]=useState('');const loss=(state.w-3)**2;
 function reset(m=method){setState(initial);setHistory([49]);setError('');setMethod(m);}
 function run(n:number){let s={...state};const h=[...history];for(let i=0;i<n;i++){const next=optimizerStep(s,lr,method);if(!Number.isFinite(next.w)||Math.abs(next.w)>10000){setError('参数已发散，实验在数值过大前停止。请减小学习率并重新开始。');break;}s=next;h.push((s.w-3)**2);}setState(s);setHistory(h);if(s.t>=10&&(s.w-3)**2<.05)onComplete(`使用 ${method} 更新 ${s.t} 步，损失降到 ${fmt((s.w-3)**2,4)}。`);}
 return <><div className="stage"><div className="stage-label">一参数优化 / L = (w − 3)²</div><div className="opt-hero"><div><span>当前参数 w</span><strong>{fmt(state.w,3)}</strong></div><div className="opt-target"><span>最优位置</span><strong>3.000</strong></div></div><LinePlot series={[history]} labels={['真实计算的损失']}/></div><div className="two-controls"><Choice label="优化器（切换会重置本轮）" value={method} set={m=>reset(m)} options={['SGD','Momentum','AdamW'].map(v=>({value:v,label:v}))}/><Range label="学习率 η" value={lr} set={setLr} min={.01} max={1.2} step={.01}/></div><div className="actions"><button className="btn primary" onClick={()=>run(10)}><Play size={16}/>运行 10 步</button><button className="btn" onClick={()=>run(1)}>单步观察</button><button className="btn icon" aria-label="重置优化器实验" onClick={()=>reset()}><RotateCcw size={16}/></button></div><Stats><Stat label="损失 L" value={loss>1e5?loss.toExponential(2):fmt(loss,4)} tone={loss<.05?'good':''}/><Stat label="当前梯度 2(w−3)" value={fmt(2*(state.w-3),3)}/><Stat label="累计更新" value={state.t}/></Stats>{error&&<Finding>{error}</Finding>}{method!=='SGD'&&<Formula>m = 0.9m + 0.1g = {fmt(state.m,4)}{method==='AdamW'&&<><br/>v = 0.999v + 0.001g² = {fmt(state.v,4)}<br/>β₁=0.9　β₂=0.999　ε=10⁻⁸　λ=0.01</>}</Formula>}<Note>这是单个参数的精确优化实验。Momentum 使用梯度的指数移动平均形式；AdamW 包含偏差校正和独立权重衰减。切换优化器会重新开始，便于比较。</Note></>;
}
export function SystemsLab({onComplete}:LabProps){
 const [p,setP]=useState('3'),[gpus,setGpus]=useState('1'),[zero,setZero]=useState('0'),[seq,setSeq]=useState('2048'),[batch,setBatch]=useState('2'),[check,setCheck]=useState(false),[tokens,setTokens]=useState(20),[checked,setChecked]=useState(false);
 const m=memoryEstimate(Number(p),Number(gpus),Number(zero),Number(seq),Number(batch),check),ok=m.total<=24&&Number(p)>=3&&tokens>=20,flops=6*Number(p)*1e9*tokens*1e9;
 return <><div className="stage"><div className="stage-label">单卡显存预算 / 每卡上限 24 GiB</div><div className="memory-top"><strong className={m.total>24?'red':'mint'}>{fmt(m.total,1)}<small> GiB / 卡</small></strong><span>{m.total>24?'超过预算':'估算可容纳'}</span></div><div className="memory-bar"><div style={{width:`${Math.min(100,m.state/Math.max(24,m.total)*100)}%`}}/><div style={{width:`${Math.min(100,m.activation/Math.max(24,m.total)*100)}%`}}/></div><div className="plot-legend"><span><i style={{background:'#3370ff'}}/>模型状态 {fmt(m.state,1)} GiB</span><span><i style={{background:'#0f6e56'}}/>激活 {fmt(m.activation,1)} GiB</span></div></div><div className="control-grid"><Choice label="参数量" value={p} set={v=>{setP(v);setChecked(false);}} options={['1','3','7','13'].map(v=>({value:v,label:v+' B（十亿）'}))}/><Choice label="GPU 数量" value={gpus} set={v=>{setGpus(v);setChecked(false);}} options={['1','2','4','8'].map(v=>({value:v,label:v+' 张'}))}/><Choice label="模型状态分片" value={zero} set={v=>{setZero(v);setChecked(false);}} options={[{value:'0',label:'无分片（数据并行）'},{value:'2',label:'ZeRO-2：梯度与优化器'},{value:'3',label:'ZeRO-3：包含参数'}]}/><Choice label="序列长度" value={seq} set={v=>{setSeq(v);setChecked(false);}} options={['1024','2048','4096','8192'].map(v=>({value:v,label:v}))}/><Choice label="每卡微批次" value={batch} set={v=>{setBatch(v);setChecked(false);}} options={['1','2','4','8'].map(v=>({value:v,label:v+' 条序列'}))}/><label className="switch-label"><Switch checked={check} onCheckedChange={v=>{setCheck(v);setChecked(false);}} aria-label="激活重计算"/>激活重计算</label></div><Range label="训练 token 数" value={tokens} set={v=>{setTokens(v);setChecked(false);}} min={10} max={100} step={10} suffix=" B" digits={0}/><Stats><Stat label="粗略训练计算量" value={(flops/1e20).toFixed(2)} unit=" ×10²⁰ FLOPs"/><Stat label="有效数据并行微批次" value={Number(gpus)*Number(batch)} unit=" 条"/></Stats><button className="btn primary" onClick={()=>{setChecked(true);if(ok)onComplete(`为 ${p}B 参数、${tokens}B token 配置 ${gpus} 张卡，估算单卡 ${fmt(m.total,1)} GiB。`);}}>检查训练配置</button>{checked&&<Finding success={ok}>{ok?'配置满足本实验约束。接下来还应实际测量峰值显存、通信和吞吐，留出余量。':m.total>24?'显存超出 24 GiB。增加 GPU 只有配合模型状态分片，才会减少每卡状态占用。':'本实验要求至少 3B 参数和 20B token。'}</Finding>}<details className="lab-details"><summary>展开预算口径与简化条件</summary><p>无分片状态占用按每参数 16 字节：BF16 参数 2、梯度 2、FP32 主权重 4、Adam 两个矩 8。ZeRO-2 保留每卡完整 BF16 参数，其余除以卡数；ZeRO-3 全部分片。</p><p>激活近似为 N × 微批次 × d × 32 层 × 2 字节 × 12，其中 d≈√(P/384)。开启重计算时乘 0.25。它是教学估算，省略注意力实现差异、通信缓冲、临时张量和碎片；不包含硬件实测吞吐。</p></details></>;
}
export function AlignmentLab({onComplete}:LabProps){
 const [selected,setSelected]=useState(-1),[margin,setMargin]=useState(-2),[beta,setBeta]=useState(.5),[steps,setSteps]=useState(0),[history,setHistory]=useState([softplus(1)]);const probability=sigmoid(beta*margin),loss=softplus(-beta*margin);
 function run(){let m=margin;const h=[...history];for(let i=0;i<10;i++){m+=2*beta*(1-sigmoid(beta*m));h.push(softplus(-beta*m));}setMargin(m);setHistory(h);setSteps(steps+10);if(sigmoid(beta*m)>.7&&selected===1)onComplete(`完成偏好对判断和 ${steps+10} 步 DPO 间距优化，配对偏好概率达到 ${fmt(sigmoid(beta*m)*100,1)}%。`);}
 return <><div className="stage"><div className="stage-label">偏好数据 / 问题：明天出门需要带伞吗？</div><p className="prompt-condition">模型没有用户所在地，也没有天气数据。选择更有依据的回答。</p><div className="preference-pair">{['不用带伞，明天一定是晴天。','我还不知道你所在的城市，也没有最新天气。告诉我城市后，可以查询预报再判断。'].map((a,i)=><button className={selected===i?'chosen':''} key={i} onClick={()=>setSelected(i)}><span>回答 {i===0?'A':'B'}</span><p>{a}</p>{selected===i&&<Check size={18}/>}</button>)}</div></div>{selected>=0&&<Finding success={selected===1}>{selected===1?'B 明确说明了缺少的信息。它没有通过自信措辞来掩盖未知。':'A 缺少天气和位置依据。“听起来果断”不等于回答正确。请重新选择。'}</Finding>}<div className="lab-controls"><Range label="DPO 系数 β（修改会重置曲线）" value={beta} set={v=>{setBeta(v);setMargin(-2);setSteps(0);setHistory([softplus(2*v)]);}} min={.1} max={1} step={.1} digits={1}/><button className="btn primary" disabled={selected!==1} onClick={run}><Play size={16}/>优化 10 步</button></div><Stats><Stat label="相对参考模型的间距" value={fmt(margin,3)}/><Stat label="配对偏好概率 σ(βΔ)" value={fmt(probability*100,1)} unit="%"/><Stat label="DPO 损失" value={fmt(loss,3)}/></Stats><LinePlot series={[history]} labels={['DPO 损失']}/><Formula>Δ = (log π(B) − log π(A)) − (log πref(B) − log πref(A))<br/>L = −log σ(βΔ)</Formula><details className="lab-details"><summary>这与 SFT、PPO 有什么不同？</summary><p>SFT：给定正确示范，用 token 级交叉熵学习回答。问题参与上下文，常只对回答部分计分。</p><p>PPO 式 RLHF：模型采样回答，奖励模型打分，用策略优化更新，同时常以 KL 项限制偏离参考模型。需要额外的采样和优化步骤。</p><p>DPO：直接学习成对偏好，相对于固定参考模型调整回答的对数概率差。这里更新的是单个间距变量，用于解释损失；真实训练通过反向传播更新网络参数。</p></details><Note>偏好数据的依据应与任务目标一致。长短、语气等代理指标可能被过度优化。本例的配对概率不是事实准确率。</Note></>;
}
