'use client';
import {useState} from 'react';
import {Play,RotateCcw,Check,ChevronUp,ChevronDown} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Range,Choice,Stats,Stat,Note,Finding,Formula,Bars,VectorPlot,LabProps} from './shared';
import {softmax,entropy,sample,fmt,corpus,pairs,mergePair,attention} from '@/lib/academy/math';
export function PredictionLab({onComplete}:LabProps){
 const [temperature,setTemp]=useState(1),[words,setWords]=useState<string[]>([]),[last,setLast]=useState('');
 const base=['地毯','椅子','月亮','代码'];
 const choices=words.length===0?base:words.length===1?['上','旁边','下面','里面']:['。','，','睡觉','休息'];
 const logits=words.length===0?[2.5,1.4,.2,-.5]:words.length===1?[2.8,1.5,1.2,-.3]:[2.5,1,1.8,1.3];
 const p=softmax(logits,temperature);
 function generate(){if(words.length>=3)return;const selected=choices[sample(p,Math.random())];const next=[...words,selected];setWords(next);setLast(`${selected}（本轮概率 ${fmt(p[choices.indexOf(selected)]*100,1)}%）`);if(next.length===3)onComplete('已运行 3 次自回归生成，观察到上下文和概率逐轮变化。');}
 return <><div className="stage prediction-stage"><div className="stage-label">CONTEXT / 已有上下文</div><div className="sentence"><span>小猫</span><span>坐在</span>{words.map((w,i)=><span className="new-token" key={i}>{w}</span>)}{words.length<3&&<span className="next-token">?</span>}</div><div className="flow-caption">上下文进入模型，得到下一 token 的概率</div><div className="prob-machine"><div className="model-core"><div className="core-mark">P</div><b>预测分布</b><small>{words.length<3?`第 ${words.length+1} 次前向计算`:'三轮生成完成'}</small></div><Bars labels={choices} values={p}/></div></div><div className="lab-controls"><Range label="温度 T" value={temperature} set={setTemp} min={.2} max={2} step={.1} digits={1}/><div className="actions"><button className="btn primary" onClick={generate} disabled={words.length>=3}><Play size={16}/>生成下一个 token</button><button className="btn icon" aria-label="重置生成" onClick={()=>{setWords([]);setLast('');}}><RotateCcw size={16}/></button></div></div><Stats><Stat label="已生成" value={words.length} unit=" / 3 token"/><Stat label="当前最高候选概率" value={fmt(Math.max(...p)*100,1)} unit="%"/><Stat label="参数是否改变" value="没有"/></Stats>{last&&<Finding success={words.length===3}>刚选中：{last}。{words.length===3?'把输出接回输入的循环已经走通。':'现在上方显示下一轮分布。'}</Finding>}<Note>这是人工设定概率表的生成实验，采样按显示的分布实际执行。后面的第 12 章会让你真正训练一个微型语言模型。温度将在第 11 章展开。</Note></>;
}
export function DataLab({onComplete}:LabProps){
 const [words,setWords]=useState(corpus),[history,setHistory]=useState<string[]>([]),[message,setMessage]=useState('');const ps=pairs(words),tokens=words.reduce((s,w)=>s+w.tokens.length*w.count,0);
 function merge(pair:string[],count:number){if(count!==ps[0].count){setMessage(`这一对出现 ${count} 次，当前最高频次是 ${ps[0].count}。BPE 每轮优先合并最高频对；频次并列时需要固定打破平局的规则。`);return;}setWords(mergePair(words,pair));const h=[...history,pair.join(' + ')+' → '+pair.join('')];setHistory(h);setMessage('合并完成。请观察词序列和相邻对频次怎样改变。');if(h.length>=3)onComplete('完成了 3 轮按频次合并，并重新统计相邻 token 对。');}
 return <><div className="stage"><div className="stage-label">小型语料 / 频次加权</div><div className="corpus">{words.map((w,i)=><div key={i}><div className="token-line">{w.tokens.map((t,j)=><span key={j}>{t}</span>)}</div><small>× {w.count}</small></div>)}</div><div className="section-label">选择本轮要合并的相邻对</div><div className="pair-grid">{ps.slice(0,8).map(p=><button key={p.pair.join('|')} className="pair" onClick={()=>merge(p.pair,p.count)}><span>{p.pair[0]} <small>+</small> {p.pair[1]}</span><strong>{p.count} 次</strong></button>)}</div></div><Stats><Stat label="已完成合并" value={history.length} unit=" 轮"/><Stat label="语料 token 总数" value={tokens}/><Stat label="词边界符" value="▁"/></Stats>{message&&<Finding success={history.length>=3}>{message}</Finding>}{history.length>0&&<div className="history">{history.map((h,i)=><span key={i}>{i+1}. {h}</span>)}</div>}<div className="actions"><button className="btn" onClick={()=>{setWords(corpus());setHistory([]);setMessage('');}}><RotateCcw size={16}/>重新分词</button></div><Note>这是经典 BPE 的小语料演示，不是某个商用分词器。计数包含词频；词边界符帮助保留边界，不能跨词合并。</Note></>;
}
export function LinearLab({onComplete}:LabProps){
 const [a,setA]=useState([1,0,0,1]),[checked,setChecked]=useState(false);const out=[2*a[0]+a[1],2*a[2]+a[3]],dot=2*out[0]+out[1],ok=Math.abs(out[0]+1)<.01&&Math.abs(out[1]-2)<.01;
 return <><div className="stage vector-stage"><div><div className="stage-label">列向量约定 / A × x</div><VectorPlot vectors={[[2,1],out]}/><div className="plot-legend"><span><i style={{background:'#829ffa'}}/>输入 (2, 1)</span><span><i style={{background:'#74e8bd'}}/>输出 ({fmt(out[0])}, {fmt(out[1])})</span></div></div><div className="matrix-work"><span className="section-label">编辑矩阵 A 的四个系数</span><div className="matrix">{a.map((v,i)=><input key={i} type="number" step=".5" min="-2" max="2" aria-label={`矩阵第 ${Math.floor(i/2)+1} 行第 ${i%2+1} 列`} value={v} onChange={e=>setA(a.map((x,j)=>i===j?Math.max(-2,Math.min(2,Number(e.target.value))):x))}/>)}</div><Formula><div>{fmt(a[0],1)} × 2 + {fmt(a[1],1)} × 1 = <b>{fmt(out[0],1)}</b></div><div>{fmt(a[2],1)} × 2 + {fmt(a[3],1)} × 1 = <b>{fmt(out[1],1)}</b></div></Formula><button className="btn primary" onClick={()=>{setChecked(true);if(ok)onComplete('矩阵变换将 (2,1) 送到 (−1,2)，点积为 0，长度保持不变。');}}><Check size={16}/>验证这次变换</button><button className="btn matrix-preset" onClick={()=>{setA([0,-1,1,0]);setChecked(false);}}>载入 90° 旋转例子</button></div></div><Stats><Stat label="输入 · 输出" value={fmt(dot)}/><Stat label="输出长度" value={fmt(Math.hypot(...out))}/><Stat label="目标输出" value="(−1, 2)"/></Stats><Finding success={ok}>{ok?'两个向量垂直，点积为 0，长度保持不变。试着观察矩阵的两列，再验证结果。':checked?'当前输出尚未达到 (−1, 2)。试着先改变矩阵的第一行，再改变第二行。':'修改矩阵会改变输出方向和长度。显示范围为 −3.5 到 3.5，超出部分会被图边界截住；数值结果仍完整。'}</Finding><Note>只把一个输入映射到目标，还不能证明矩阵对所有向量都实现 90° 旋转。标准旋转矩阵是 [[0, −1], [1, 0]]，它的两列是旋转后的两个基向量。</Note></>;
}
export function AttentionLab({onComplete}:LabProps){
 const [x,setX]=useState(2),[y,setY]=useState(0);const a=attention([x,y,0,0]),labels=['小猫','坐在','地毯'],ok=a.weights[2]>.6;
 return <><div className="stage attention-stage"><div className="stage-label">一个查询 / 三组键和值 / dₖ = 4</div><div className="attention-query"><span>当前查询 Q</span><strong>({fmt(x,1)}, {fmt(y,1)}, 0, 0)</strong></div><svg className="attention-links" viewBox="0 0 600 80" aria-hidden="true">{a.weights.map((w,i)=><path key={i} d={`M300,0 C300,50 ${100+i*200},30 ${100+i*200},80`} stroke="#74e8bd" strokeOpacity={.25+w*.75} strokeWidth={2+w*11} fill="none"/>)}</svg><div className="attention-tokens">{labels.map((t,i)=><div className={i===2?'target':''} key={t}><b>{t}</b><small>K = ({a.keys[i].join(', ')})</small><span>{fmt(a.weights[i]*100,1)}%</span><small>V = ({a.values[i].join(', ')})</small></div>)}</div><div className="attention-output"><span>混合后的值向量</span><strong>({fmt(a.out[0])}, {fmt(a.out[1])})</strong></div></div><div className="two-controls"><Range label="Q 的第 1 个分量" value={x} set={setX} min={-2} max={4} step={.1} digits={1}/><Range label="Q 的第 2 个分量" value={y} set={setY} min={-2} max={4} step={.1} digits={1}/></div><Formula>点积 ÷ 2 = [{a.scores.map(s=>fmt(s)).join(', ')}]<br/>softmax = [{a.weights.map(w=>fmt(w,3)).join(', ')}]<br/>输出 = {a.weights.map((w,i)=>`${fmt(w,3)}×(${a.values[i].join(',')})`).join(' + ')}</Formula><div className="actions"><button className="btn primary" disabled={!ok} onClick={()=>onComplete(`地毯权重达到 ${fmt(a.weights[2]*100,1)}%，已用同一权重验证值向量混合。`)}><Check size={16}/>验证信息路由</button><button className="btn" onClick={()=>{setX(2);setY(0);}}><RotateCcw size={16}/>恢复讲义例子</button></div><Note>连线粗细对应实际计算的注意力权重。它表示信息混合比例；不表示词的事实正确率。</Note></>;
}
export function CausalLab({onComplete}:LabProps){
 const [mask,setMask]=useState(true),[saw,setSaw]=useState(false),[query,setQuery]=useState(2),[length,setLength]=useState('8'),[distance,setDistance]=useState(2);
 const n=Number(length),rows=Array.from({length:n},(_,i)=>softmax(Array.from({length:n},(_,j)=>mask&&j>i?-Infinity:Math.cos(i-j)*1.5+j*.1))),future=rows[query].reduce((s,w,j)=>s+(j>query?w:0),0),angle=distance*.4;
 function toggle(b:boolean){setMask(b);if(!b)setSaw(true);}
 return <><div className="stage"><div className="stage-label">因果注意力矩阵 / 点击行号选择查询</div><div className="heatmap" style={{gridTemplateColumns:`30px repeat(${n}, minmax(0,1fr))`}}><span/>{Array.from({length:n},(_,i)=><span className="heat-label" key={'l'+i}>{i+1}</span>)}{rows.map((row,i)=><div className="heat-row" key={i}><button aria-label={`查看查询位置 ${i+1}`} className={'heat-label '+(query===i?'selected':'')} onClick={()=>setQuery(i)}>{i+1}</button>{row.map((w,j)=><button key={j} onClick={()=>setQuery(i)} className={'heat-cell '+(i===query?'active':'')} title={`查询 ${i+1} → 键 ${j+1}: ${fmt(w*100,1)}%`} aria-label={`查询 ${i+1}，键 ${j+1}，权重 ${fmt(w*100,1)}%`} style={{background:w===0?'#121a28':`rgba(116,232,189,${.12+w*.85})`}}>{n===8?(w===0?'—':fmt(w,2)):''}</button>)}</div>)}</div><div className="heat-legend"><span>纵轴：查询位置　横轴：被读取位置</span><span>— = 被遮罩，权重为 0</span></div></div><div className="lab-controls"><label className="switch-label"><Switch checked={mask} onCheckedChange={toggle} aria-label="因果遮罩"/><span>因果遮罩 {mask?'开启':'关闭'}</span></label><Choice label="序列长度" value={length} set={v=>{setLength(v);setQuery(Math.min(query,Number(v)-1));}} options={[{value:'8',label:'8 个 token'},{value:'16',label:'16 个 token'}]}/></div><Stats><Stat label={`位置 ${query+1} 读到的未来权重`} value={fmt(future*100,1)} unit="%" tone={future>0?'warn':'good'}/><Stat label="分数矩阵元素" value={n*n}/><Stat label="有效因果位置" value={n*(n+1)/2}/></Stats><button className="btn primary" disabled={!saw||!mask} onClick={()=>onComplete('已对比有无遮罩的分布；因果遮罩使所有未来位置权重为 0。')}>记录遮罩实验</button><details className="lab-details"><summary>再深入一步：位置如何进入点积？</summary><p>下图只画 RoPE 的一对坐标，频率设为 0.4 弧度/位置。查询在位置 0，键在位置 Δ；两者原始方向相同。</p><Range label="相对位置 Δ" value={distance} set={setDistance} min={0} max={8} step={1} digits={0}/><div className="rope-row"><VectorPlot vectors={[[2,0],[2*Math.cos(angle),2*Math.sin(angle)]]} labels={['Q','旋转后的 K']} size={210}/><Formula>角度 = 0.4 × {distance}<br/>Q·K = 4cos({fmt(angle)})<br/> = {fmt(4*Math.cos(angle))}</Formula></div><p>点积现在随相对位置变化。完整 RoPE 同时旋转不同位置的 Q/K，并使用多种频率；它不会阻止看见未来。</p></details><Note>本矩阵使用固定公式生成教学分数，没有从语料训练。遮罩、softmax、位置旋转和矩阵大小均为实际计算。</Note></>;
}
const modules=[{id:'embed',name:'Embedding',desc:'ID 查表，得到 token 向量',shape:'[B, N] → [B, N, d]'},{id:'attn',name:'RMSNorm + Masked Attention',desc:'读取上下文，输出映射回 d',shape:'[B, N, d] → [B, N, d]'},{id:'res1',name:'第一次残差相加',desc:'加回 Attention 子层输入',shape:'X + Attention(RMSNorm(X))'},{id:'ffn',name:'RMSNorm + SwiGLU',desc:'逐位置非线性变换',shape:'d → d_ff → d'},{id:'res2',name:'第二次残差相加',desc:'加回 FFN 子层输入',shape:'X + FFN(RMSNorm(X))'},{id:'norm',name:'最终 RMSNorm',desc:'所有 Transformer 块之后',shape:'[B, N, d]'},{id:'head',name:'Linear + Softmax',desc:'投影到词表，形成概率',shape:'[B, N, d] → [B, N, V]'}];
export function ArchitectureLab({onComplete}:LabProps){
 const [order,setOrder]=useState([0,3,2,1,4,6,5]),[checked,setChecked]=useState(false),[width,setWidth]=useState('256'),[heads,setHeads]=useState('8');const ok=order.every((v,i)=>v===i),compatible=Number(width)%Number(heads)===0;
 function move(i:number,d:number){setChecked(false);const a=[...order];[a[i],a[i+d]]=[a[i+d],a[i]];setOrder(a);}
 return <><div className="stage architecture-stage"><div className="stage-label">修复计算流程 / 上下移动模块</div><div className="module-stack">{order.map((v,i)=><div className={'module '+(checked?(v===i?'correct':'incorrect'):'')} key={v}><span className="module-order">{String(i+1).padStart(2,'0')}</span><div><b>{modules[v].name}</b><small>{modules[v].desc}</small><code>{modules[v].shape}</code></div><div className="module-movers"><button disabled={i===0} onClick={()=>move(i,-1)} aria-label={`上移 ${modules[v].name}`}><ChevronUp size={16}/></button><button disabled={i===order.length-1} onClick={()=>move(i,1)} aria-label={`下移 ${modules[v].name}`}><ChevronDown size={16}/></button></div></div>)}</div></div><div className="two-controls"><Choice label="模型宽度 d" value={width} set={setWidth} options={['256','384','512'].map(v=>({value:v,label:v}))}/><Choice label="查询头数 h" value={heads} set={setHeads} options={['4','6','8'].map(v=>({value:v,label:v}))}/></div><Stats><Stat label="每头维度 d / h" value={compatible?Number(width)/Number(heads):'无法整除'} tone={compatible?'good':'warn'}/><Stat label="序列长度 N" value="保持不变"/></Stats><button className="btn primary" onClick={()=>{setChecked(true);if(ok&&compatible)onComplete('模块顺序与头维度均通过检查；理解了一个 PreNorm 解码器块的计算流程。');}}>检查模型结构</button>{checked&&<Finding success={ok&&compatible}>{ok?(compatible?'结构通过：中间四步构成一个块，可重复堆叠多层；末尾才归一化并映射到词表。':'顺序正确，但 d_model 必须能被查询头数整除。'):'红框模块仍在错误位置。先找到 Attention 子层，再找到两次残差相加各自的输入。'}</Finding>}<Note>这里展示现代 PreNorm 解码器。省略批处理细节、位置旋转和输出权重共享；原理手册与实现代码会补充。</Note></>;
}
