'use client';
import {ReactNode} from 'react';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {CheckCircle2,FlaskConical} from 'lucide-react';
import {fmt} from '@/lib/academy/math';
export function Range({label,value,set,min=0,max=1,step=.01,suffix='',digits=2}:{label:string;value:number;set:(v:number)=>void;min?:number;max?:number;step?:number;suffix?:string;digits?:number}) {return <div className="range"><div><label>{label}</label><output>{fmt(value,digits)}{suffix}</output></div><Slider ref={el=>{if(el)el.querySelectorAll('[role="slider"]').forEach(t=>t.setAttribute('aria-label',label));}} aria-label={label} value={[value]} onValueChange={v=>set(v[0])} min={min} max={max} step={step}/><div className="range-extents"><span>{min}{suffix}</span><span>{max}{suffix}</span></div></div>}
export function Choice({label,value,set,options}:{label:string;value:string;set:(s:string)=>void;options:{value:string,label:string}[]}) {return <div className="choice"><label>{label}</label><Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function Stat({label,value,unit,tone=''}:{label:string;value:ReactNode;unit?:string;tone?:string}){return <div className={'stat '+tone}><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>}
export function Stats({children}:{children:ReactNode}){return <div className="stats">{children}</div>}
export function Note({children}:{children:ReactNode}){return <div className="lab-note"><FlaskConical size={16}/><div>{children}</div></div>}
export function Finding({children,success=false}:{children:ReactNode;success?:boolean}){return <div className={'finding '+(success?'success':'')} aria-live="polite">{success&&<CheckCircle2 size={19}/>}<div>{children}</div></div>}
export function Formula({children}:{children:ReactNode}){return <div className="formula">{children}</div>}
export function Bars({labels,values,highlight=-1,other,color}:{labels:string[];values:number[];highlight?:number;other?:number[];color?:string}){return <div className="bars">{labels.map((label,i)=><div className={'bar-row '+(i===highlight?'highlight':'')} key={label}><span>{label}</span><div className="bar-track">{other&&<div className="bar-ghost" style={{width:`${Math.round(other[i]*100000)/1000}%`}}/>}<div className="bar-fill" style={{width:`${Math.round(Math.max(0,Math.min(1,values[i]))*100000)/1000}%`,background:color}}/></div><output>{fmt(values[i]*100,1)}<small>%</small></output></div>)}</div>}
export function LinePlot({series,labels=['损失'],height=230}:{series:number[][];labels?:string[];height?:number}) {
 const all=series.flat().filter(Number.isFinite),max=Math.max(0.05,...all),min=0,w=620,h=height,p=42;
 const colors=['#0f6e56','#b86e00','#3370ff'];
 return <div className="plot"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={labels.join('、')+'变化曲线'}>{[0,.25,.5,.75,1].map(t=><g key={t}><line x1={p} y1={h-p-t*(h-2*p)} x2={w-p/2} y2={h-p-t*(h-2*p)} stroke="#dee0e3" strokeDasharray="3 5"/><text x={p-8} y={h-p-t*(h-2*p)+4} textAnchor="end" fill="#8f959e" fontSize="12">{fmt(min+t*(max-min),max>10?0:2)}</text></g>)}{series.map((arr,s)=><polyline key={s} fill="none" stroke={colors[s]} strokeWidth="2.5" points={arr.map((v,i)=>`${p+i/Math.max(1,arr.length-1)*(w-p*1.5)},${h-p-(Math.max(0,Math.min(max,v))-min)/(max-min)*(h-2*p)}`).join(' ')}/>)}<text x={p} y={h-12} fill="#8f959e" fontSize="12">0</text><text x={w-p/2} y={h-12} textAnchor="end" fill="#8f959e" fontSize="12">{Math.max(...series.map(s=>s.length))-1} 步</text></svg><div className="plot-legend">{labels.map((l,i)=><span key={l}><i style={{background:colors[i]}}/>{l}</span>)}</div></div>
}
export function VectorPlot({vectors,labels=['输入','输出'],size=300}:{vectors:number[][];labels?:string[];size?:number}){
 const r=3.5,c=size/2,s=(size-55)/(r*2),colors=['#3370ff','#0f6e56','#b86e00'];
 return <svg className="vector-plot" viewBox={`0 0 ${size} ${size}`} role="img" aria-label={vectors.map((v,i)=>`${labels[i]}向量 (${fmt(v[0])},${fmt(v[1])})`).join('；')}><defs>{colors.map((color,i)=><marker key={i} id={'arrow-'+i} markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 Z" fill={color}/></marker>)}</defs>{[-3,-2,-1,0,1,2,3].map(i=><g key={i}><line x1={c+i*s} y1="20" x2={c+i*s} y2={size-20} stroke={i===0?'#8f959e':'#e8eaed'}/><line x1="20" y1={c+i*s} x2={size-20} y2={c+i*s} stroke={i===0?'#8f959e':'#e8eaed'}/>{i!==0&&<text x={c+i*s+3} y={c+15} fill="#646a73" fontSize="11">{i}</text>}</g>)}{vectors.map((v,i)=><g key={i}><line x1={c} y1={c} x2={c+Math.max(-r,Math.min(r,v[0]))*s} y2={c-Math.max(-r,Math.min(r,v[1]))*s} stroke={colors[i]} strokeWidth="2.5" markerEnd={`url(#arrow-${i})`}/><circle cx={c+Math.max(-r,Math.min(r,v[0]))*s} cy={c-Math.max(-r,Math.min(r,v[1]))*s} r="4" fill={colors[i]}/></g>)}<text x={size-16} y={c-8} fill="#8f959e" fontSize="12">x</text><text x={c+8} y="16" fill="#8f959e" fontSize="12">y</text></svg>
}
export type LabProps={onComplete:(evidence:string)=>void;done:boolean};
