"""Build commit-pinned source excerpts, never guessed line numbers."""
import json
from pathlib import Path
ROOT=Path(__file__).parent
REVISIONS={r['name']:r for r in json.loads((ROOT/'evidence/revisions.json').read_text()) if 'sha' in r}
S=[]
def add(id,repo,file,needle,title,count=45,offset=0):
    path=ROOT/'repos'/repo/file; lines=path.read_text().splitlines()
    found=next((i for i,line in enumerate(lines) if needle in line),None)
    if found is None:raise ValueError((id,file,needle))
    start=max(0,found+offset);end=min(len(lines),start+count);r=REVISIONS[repo]
    S.append(dict(id=id,repo=repo,file=file,title=title,sha=r['sha'],line=start+1,end=end,url=f"https://github.com/{r['repo']}/blob/{r['sha']}/{file}#L{start+1}-L{end}",kind='source',excerpt='\n'.join(f'{i+1:>5}  {lines[i]}' for i in range(start,end))))

add('cx-entry','codex','codex-rs/core/src/session/handlers.rs','async fn submission_loop','输入入口：submission_loop',55)
add('cx-loop','codex','codex-rs/core/src/session/turn.rs','async fn run_turn','Codex：run_turn',55)
add('cx-follow','codex','codex-rs/core/src/session/turn.rs','let needs_follow_up =','工具／待处理输入驱动下一轮',55)
add('cx-stop','codex','codex-rs/core/src/session/turn.rs','if !needs_follow_up {','停止前仍经过 Stop hooks',63)
add('cx-prompt','codex','codex-rs/core/src/session/turn.rs','pub(crate) fn build_prompt','Prompt 与增量 tool schema',35)
add('cx-input','codex','codex-rs/core/src/session/mod.rs','async fn build_initial_context_with_world_state','初始上下文与 developer fragments',60)
add('cx-agents','codex','codex-rs/core/src/context/world_state/agents_md.rs','impl WorldStateSection','AGENTS.md 作为 contextual user fragment',48)
add('cx-retry','codex','codex-rs/core/src/session/turn.rs','async fn run_sampling_request','采样请求与重试状态',100)
add('cx-parallel','codex','codex-rs/core/src/tools/parallel.rs','let guard = if supports_parallel','读锁并行／写锁独占',34)
add('cx-route','codex','codex-rs/core/src/tools/router.rs','pub struct ToolRouter','工具路由',48)
add('cx-policy','codex','codex-rs/core/src/tools/orchestrator.rs','    pub async fn run','审批、sandbox、执行尝试',220)
add('cx-tools','codex','codex-rs/core/src/tools/spec_plan.rs','pub(crate) fn build_core_tool_registry','动态工具注册表',40)
add('cx-compact','codex','codex-rs/core/src/compact.rs','let summary_text = format!','压缩历史、重注入上下文、记录 compact',52)
add('cx-history','codex','codex-rs/core/src/context_manager/history.rs','Tool output truncation applies only','模型历史截断不等于 rollout 删除',70)
add('cx-spawn','codex','codex-rs/core/src/agent/control/spawn.rs','async fn spawn_agent_internal','子 Agent 创建与配置继承',65)
add('cx-inherit','codex','codex-rs/core/src/agent/control/spawn.rs','intersect_effective_permission_profiles(&authority','恢复子任务时收窄到父权限',82,-62)
add('cx-sandbox','codex','codex-rs/sandboxing/src/manager.rs','    pub fn select_initial(','Sandbox 选择与命令变换入口',110)
add('ki-loop','kimi-cli','src/kimi_cli/soul/kimisoul.py','    async def _agent_loop','KimiSoul：MCP 初始化与 step loop',148)
add('ki-step','kimi-cli','src/kimi_cli/soul/kimisoul.py','        async def _run_step_once','模型请求：provider/system/toolset/history',62)
add('ki-stop','kimi-cli','src/kimi_cli/soul/kimisoul.py','        if result.tool_calls:','no_tool_calls 是停止原因',10)
add('ki-hooks','kimi-cli','src/kimi_cli/soul/kimisoul.py','            # --- Stop hook','Stop hook 阻止结束',25)
add('ki-agents','kimi-cli','src/kimi_cli/soul/agent.py','async def load_agents_md','AGENTS 文件发现与合并',65)
add('ki-builtins','kimi-cli','src/kimi_cli/soul/agent.py','class BuiltinSystemPromptArgs','repo/环境/skills 的 system 模板变量',30)
add('ki-compact','kimi-cli','src/kimi_cli/soul/compaction.py','def should_auto_compact','双条件压缩阈值',22)
add('ki-summary','kimi-cli','src/kimi_cli/soul/compaction.py','class SimpleCompaction','摘要模型调用与尾部保留',100)
add('ki-context','kimi-cli','src/kimi_cli/soul/context.py','    async def revert_to','JSONL checkpoint 回退',70)
add('ki-restore','kimi-cli','src/kimi_cli/soul/context.py','    async def restore','Context restore 与 token estimate',40)
add('ki-kosong','kimi-cli','packages/kosong/src/kosong/__init__.py','async def step','Kosong 的流式工具派发',90)
add('ki-toolset','kimi-cli','src/kimi_cli/soul/toolset.py','    def begin_step','工具重复调用的跨步状态',55)
add('ki-shell','kimi-cli','src/kimi_cli/tools/shell/__init__.py','    async def __call__','Shell：审批通过后执行',60)
add('ki-approval','kimi-cli','src/kimi_cli/soul/approval.py','    async def request','Kimi 审批协议',85)
add('ki-subagent','kimi-cli','src/kimi_cli/subagents/runner.py','    async def run(self','子任务 runner',65)
add('ki-git','kimi-cli','src/kimi_cli/subagents/git_context.py','async def collect_git_context','explore 子 Agent 的 Git context',62)
add('ki-bg','kimi-cli','src/kimi_cli/tools/shell/__init__.py','MAX_FOREGROUND_TIMEOUT','前台／后台进程预算',35)
add('ds-loop','deepseek-harness','packages/core/agent-loop/src/agent.ts','  private async turn()','DeepSeek：turn → preStep → step',87)
add('ds-stop','deepseek-harness','packages/core/agent-loop/src/agent.ts',"if (finish.kind === 'max-tokens')",'停止原因与 tool continuation',13)
add('ds-request','deepseek-harness','packages/core/agent-loop/src/agent.ts','const boundaryMessages = session.deriveMessages()','从持久事件派生并冻结模型请求',48)
add('ds-prompt','deepseek-harness','packages/core/system-prompt/src/index.ts','  async assemble(','system prompt 与 tool schemas 装配',72)
add('ds-tools','deepseek-harness','packages/core/tools/src/index.ts','export class ToolRuntime','ToolRuntime：schema、执行、guard',40)
add('ds-pipeline','deepseek-harness','packages/core/tools/src/index.ts',"'tools/pre-execute'",'工具执行 waterfall hooks',36)
add('ds-parallel','deepseek-harness','packages/core/agent-loop/src/tool-calls.ts','export async function executeToolCalls','并行组、独占屏障、按模型顺序提交结果',100)
add('ds-retry','deepseek-harness','packages/core/agent-loop/src/agent.ts',"if (finish.kind === 'error'",'失败 attempt 落盘与 request-error 重试',30)
add('ds-repair','deepseek-harness','packages/core/session/src/repair.ts','export function','不完整 tool/step/turn 尾部修复',85)
add('ds-persist','deepseek-harness','packages/session/session-persistence/src/index.ts',' * Durable append-only','持久化 append 与 flush 的保证不同',68)
add('ds-compact','deepseek-harness','packages/compaction/compaction-basic/src/index.ts','  override async compactIfNeeded','压力、overflow、prune、summary',82)
add('ds-sandbox','deepseek-harness','packages/sandbox/sandbox-local/src/index.ts',' * Local sandbox backend','平台 runner 与 fail-closed',28)
add('ds-subagent','deepseek-harness','packages/subagent/subagent-in-process-driver/src/index.ts','export async function startInProcessRun','in-process 子 Agent driver',112)
add('ds-architecture','deepseek-harness','docs/architecture.md','## Turn flow','官方架构与事件生命周期',60)
add('ge-client','gemini-cli','packages/core/src/core/client.ts','  async *sendMessageStream','GeminiClient 外层流式请求',65)
add('ge-turn','gemini-cli','packages/core/src/core/turn.ts','export class Turn','Turn → GeminiChat → provider stream',60)
add('ge-schema','gemini-cli','packages/core/src/core/client.ts','  async setTools','functionDeclarations 注册',25)
add('ge-input','gemini-cli','packages/core/src/core/geminiChat.ts','systemInstruction: this.systemInstruction','Gemini API 的 systemInstruction/tools',27,-6)
add('ge-system','gemini-cli','packages/core/src/core/client.ts','    const systemMemory = this.config.getSystemInstructionMemory();','系统记忆进入 systemInstruction',37,-4)
add('ge-history','gemini-cli','packages/core/src/core/geminiChat.ts','  getHistory(curated: boolean = false)','完整历史与 curated 历史',49,-18)
add('ge-scheduler','gemini-cli','packages/core/src/scheduler/scheduler.ts','// If the first tool is parallelizable','连续可并行工具分组',52,-8)
add('ge-policy','gemini-cli','packages/core/src/scheduler/scheduler.ts','const { decision: policyDecision','执行前策略检查',64)
add('ge-next','gemini-cli','packages/core/src/core/client.ts','    if (!turn.pendingToolCalls.length','nextSpeaker 继续检查',37)
add('ge-nextprompt','gemini-cli','packages/core/src/utils/nextSpeakerChecker.ts','const CHECK_PROMPT','nextSpeaker 只分析上一条回复',22)
add('ge-collapse','gemini-cli','packages/core/src/context/chatCompressionService.ts','export function collapseOlderFunctionResponses','旧工具输出折叠及最近轮保护',130)
add('ge-compress','gemini-cli','packages/core/src/context/chatCompressionService.ts','  async compress(','压缩触发与失败处理',90)
add('ge-record','gemini-cli','packages/core/src/services/chatRecordingService.ts','export class ChatRecordingService','会话记录服务',58)
add('ge-agent','gemini-cli','packages/core/src/agents/local-subagent-protocol.ts','export class','本地子 Agent 协议',60)
add('ge-sandbox','gemini-cli','packages/core/src/sandbox/linux/LinuxSandboxManager.ts','export class','Linux SandboxManager',62)
add('oc-loop','opencode','packages/opencode/src/session/prompt.ts','    const runLoop:','OpenCode：数据库历史驱动循环',82)
add('oc-llm','opencode','packages/opencode/src/session/llm.ts','        result: streamText({','统一 Provider 流与 tool repair',72)
add('oc-compact','opencode','packages/opencode/src/session/compaction.ts','    const prune =','prune 与摘要分离',47)
add('oc-permission','opencode','packages/opencode/src/permission/index.ts','    const ask =','allow / deny / ask',41)
add('oc-worktree','opencode','packages/opencode/src/worktree/index.ts','    const setup =','创建 Git worktree',52)
add('oc-snapshot','opencode','packages/opencode/src/snapshot/index.ts','git','Git snapshot 实现',60)
add('oc-subagent','opencode','packages/opencode/src/tool/task.ts','Tool.define','task 工具与子 session',65)
add('oc-process','opencode','packages/opencode/src/session/processor.ts','      const process =','流处理、重试、终止和压缩反馈',70)
add('mi-loop','mini-swe-agent','src/minisweagent/agents/default.py','    def run(','最小循环与每步保存',76)
add('mi-exec','mini-swe-agent','src/minisweagent/agents/default.py','    def execute_actions','顺序执行工具／观察回注',10)
add('mi-stop','mini-swe-agent','src/minisweagent/environments/local.py','    def _check_finished','stdout 提交标记产生 Submitted',17)
add('mi-shell','mini-swe-agent','src/minisweagent/environments/local.py','def _run(','本地 shell 与进程组 timeout',27)
add('cl-transport','claude-sdk','src/claude_agent_sdk/_internal/transport/subprocess_cli.py','    def _build_command','SDK 配置变成 CLI 参数',75)
add('cl-control','claude-sdk','src/claude_agent_sdk/_internal/query.py','    async def _handle_control_request','双向控制协议与 can_use_tool',69)
add('cl-options','claude-sdk','src/claude_agent_sdk/types.py','    agents: dict[str, AgentDefinition]','subagent / skills / sandbox / plugin 配置边界',63)
add('cl-hook','claude-code','plugins/ralph-wiggum/hooks/stop-hook.sh','# Check for completion promise','公开 Stop hook：匹配 promise',60)
add('cl-log','claude-code','CHANGELOG.md','Fixed mid-response API timeouts','官方说明：超时、压缩、resume 行为',18,-3)
add('cl-memory','claude-code','CHANGELOG.md',"Fixed a folder's CLAUDE.md",'官方说明：CLAUDE.md 在 resume / compaction 后重复加载',8,-2)
add('cl-worktree','claude-code','CHANGELOG.md','Fixed subagents spawned with worktree isolation','官方说明：worktree 子任务与后台状态',12,-4)
add('cl-store','claude-sdk','src/claude_agent_sdk/types.py','    enable_file_checkpointing: bool','SDK 的文件 checkpoint 与 session store 接口',36)
add('cl-sandbox','claude-sandbox','src/sandbox/sandbox-manager.ts','async function wrapWithSandbox','公开 sandbox wrapper',75)
add('cl-network','claude-sandbox','src/sandbox/sandbox-manager.ts','  for (const deniedDomain','代理域名策略',32)

for id,file,url,title in [
 ('cloud-current','codex-current-cloud.html.txt','https://developers.openai.com/codex/environments/cloud-environments','Codex Cloud 当前环境：独立 workspace 与保存状态'),
 ('cloud-legacy','codex-cloud.html.txt','https://developers.openai.com/codex/cloud/environments','Codex Cloud Legacy：不要混用旧文档')]:
    S.append(dict(id=id,repo='official-doc',file=file,title=title,url=url,kind='official',excerpt=(ROOT/'evidence'/file).read_text()[:17000]))
for s in S:
    if s['file'].endswith('.md'):
        s['kind']='official'
(ROOT/'evidence/sources.json').write_text(json.dumps(S,ensure_ascii=False,indent=2))
print(f'{len(S)} pinned source/document entries')
