import {useId} from 'react';
import type {Run} from '@/lib/workshop/types';
import {linearFit,sigmoid} from '@/lib/workshop/numerics';

/** These visuals read the recorded run, never the edited-but-unrun controls. */
export function MechanismVisual({chapterId,run}:{chapterId:string;run:Run}) {
 const uid=useId().replace(/[^a-zA-Z0-9]/g,'');
 if(chapterId==='f3')return <figure className="ws-mechanism"><figcaption><b>同一条输入，不同的计分位置</b><span>蓝色参与损失，浅色保留为上下文；灰色 padding 被忽略。</span></figcaption><div className="ws-token-strip">{run.result.rows.map((row,i)=><div key={i} className={row[1]==='计分'?'scored':row[0]==='<pad>'?'padding':''}><code>{row[0]}</code><small>{row[1]}</small><span>{row[1]==='计分'?`−ln p = ${row[3]}`:'不进入损失平均'}</span></div>)}</div><p>因果方向从左向右。用户问题即使不计分，仍可影响后面的回答。</p></figure>;
 if(chapterId==='f5'){
   const r=linearFit(run.settings.steps,run.settings.lr,run.settings.noise,0),points=[[0,1,1],[0,-1,0],[.2,.8,1],[-.2,-.8,0]],sx=(x:number)=>210+x*115,sy=(y:number)=>160-y*115;
   const y1=(-r.w[0]*-1.35-r.b)/r.w[1],y2=(-r.w[0]*1.35-r.b)/r.w[1];
   return <figure className="ws-mechanism"><figcaption><b>参数改变了分类边界</b><span>四个点是真实微型训练里的目标样本。坐标是人工特征，不是词向量。</span></figcaption><svg className="ws-classifier" viewBox="0 0 430 330" role="img" aria-label="二维分类边界与四个目标样本。每个点旁显示真实标签和模型预测正类概率。"><defs><clipPath id={`classifier-${uid}`}><rect x="45" y="15" width="330" height="290"/></clipPath></defs><rect x="45" y="15" width="330" height="290" rx="6" fill="#f7f9fd"/><line x1="45" x2="375" y1="160" y2="160" stroke="#c7d4e8"/><line x1="210" x2="210" y1="15" y2="305" stroke="#c7d4e8"/><g clipPath={`url(#classifier-${uid})`}>{Math.abs(r.w[1])>1e-8?<line x1={sx(-1.35)} x2={sx(1.35)} y1={sy(y1)} y2={sy(y2)} stroke="#567cba" strokeWidth="2" strokeDasharray="6 5"/>:<line x1={sx(-r.b/r.w[0])} x2={sx(-r.b/r.w[0])} y1="15" y2="305" stroke="#567cba" strokeWidth="2"/>}</g>{points.map(([x,y,target],i)=><g key={i}><circle cx={sx(x)} cy={sy(y)} r="7" fill={target?'#007c78':'#ba7439'} stroke="white" strokeWidth="2"/><text x={i===3?sx(x)-13:sx(x)+13} textAnchor={i===3?'end':'start'} y={sy(y)+(i===2||i===3?13:-8)} fontSize="11" fill="#526b8f">标签 {target}，P(1)={(sigmoid(r.w[0]*x+r.w[1]*y+r.b)*100).toFixed(1)}%</text></g>)}<text x="373" y="177" textAnchor="end" fontSize="10" fill="#8092ac">横向特征</text><text x="219" y="27" fontSize="10" fill="#8092ac">纵向特征</text><text x="210" y="325" textAnchor="middle" fontSize="11" fill="#687f9f">虚线：w·x+b=0，两类各 50% 的边界</text></svg><p>对照更新前后，观察同一个点的概率变化。边界能拟合的是这里定义的人工任务。</p></figure>;
 }
 if(chapterId==='f6')return <figure className="ws-mechanism"><figcaption><b>原矩阵旁边，加一个能学习的小增量</b><span>示意单个 4096 × 4096 投影；矩形宽度只表达形状，不按实际比例绘制。</span></figcaption><div className="ws-lora-diagram"><div className="ws-matrix full"><b>W</b><span>4096 × 4096</span><small>{run.settings.method===0?'全量更新':'冻结的底座'}</small></div><strong>+</strong><div className="ws-matrix narrow"><b>B</b><span>4096 × {run.settings.rank}</span></div><strong>×</strong><div className="ws-matrix flat"><b>A</b><span>{run.settings.rank} × 4096</span></div></div><p>{run.settings.method===0?'当前选的是全量更新：直接训练 W。下面的 A/B 表示另外两种适配器方案，用于比较。':`当前 r=${run.settings.rank}：B×A 仍得到 4096×4096 的增量，但只训练 ${(2*4096*run.settings.rank).toLocaleString()} 个适配器参数。`} 图中省略了 α/r 缩放系数。</p></figure>;
 if(chapterId==='d5'||chapterId==='d6')return <figure className="ws-mechanism"><figcaption><b>同时看第一名，也看次优选项</b><span>同一训练温度下的教师与学生；长度表示概率。</span></figcaption><div className="ws-probability-legend"><span><i/>教师</span><span><i/>学生</span></div><div className="ws-probability-bars">{run.result.rows.map((row,i)=><div key={i}><b>{row[0]}</b><div>{[1,2].map((column,j)=><div className={j?'student':'teacher'} key={column}><span style={{width:`${Math.max(0,Math.min(100,parseFloat(String(row[column]))||0))}%`}}/><small>{row[column]}</small></div>)}</div></div>)}</div><p>第一名相同，分布也可能很不一样。KL 比较的是整张概率分布。</p></figure>;
 if(chapterId==='d11')return <figure className="ws-mechanism"><figcaption><b>路由器把请求分到哪里</b><span>看错分发生在哪一条路上，再解释质量与成本。</span></figcaption><div className="ws-routing-map">{run.result.rows.map((row,i)=><div key={i}><b>{row[0]}</b><div><span className={i===0?'':'caution'}>{Number(row[1]).toLocaleString()} 次 → 教师<small>{i===0?'正确识别困难任务':'普通题误升级，增加开销'}</small></span><span className={i===0?'caution':''}>{Number(row[2]).toLocaleString()} 次 → 学生<small>{i===0?'难题漏报，质量受影响':'普通任务留给学生'}</small></span></div></div>)}</div></figure>;
 return null;
}
