import type {Lab, Control, Result, Settings} from './types';
import {mean, round, sum, linearFit, sigmoid, softplus, wilson} from './numerics';
export const slider=(key:string,label:string,initial:number,min:number,max:number,step:number,help:string,unit=''):Control=>({key,label,initial,min,max,step,help,unit});
export const choice=(key:string,label:string,labels:string[],initial=0,help=''):Control=>({key,label,help,initial,options:labels.map((label,value)=>({label,value}))});
export const toggle=(key:string,label:string,initial=0,help=''):Control=>choice(key,label,['关闭','开启'],initial,help);
const metric=(label:string,value:number|string,detail?:string)=>({label,value:String(value),detail});
const percent=(v:number)=>`${round(v*100,1)}%`;
const records=[
 {id:'A1',intent:'退款',text:'订单未发货，请取消',answer:'检查状态后发起取消',flag:'合格',group:'用户甲'},
 {id:'A2',intent:'退款',text:'订单未发货，请取消',answer:'检查状态后发起取消',flag:'重复',group:'用户甲'},
 {id:'B1',intent:'物流',text:'我的手机号 13800000000，查快递',answer:'根据订单查询',flag:'隐私',group:'用户乙'},
 {id:'C1',intent:'退款',text:'用了半年，随便退吗',answer:'任何时候都无条件退款',flag:'矛盾',group:'用户丙'},
 {id:'D1',intent:'物流',text:'物流三天未更新',answer:'查询轨迹并升级人工',flag:'合格',group:'用户丁'},
 {id:'E1',intent:'异常',text:'没有购买记录却收到扣款',answer:'核验身份并升级人工',flag:'合格',group:'用户戊'},
 {id:'F1',intent:'退款',text:'重复付款了',answer:'核验支付流水后处理',flag:'合格',group:'用户己'},
 {id:'G1',intent:'异常',text:'包裹内物品破损',answer:'收集证据并按规则处理',flag:'合格',group:'用户庚'},
];
export const finetuneLabs:Lab[]=[
{title:'先决定：到底改什么',context:'你负责一家电商的助手。把一个业务问题交给合适的干预方式，避免把每件事都变成训练。',mode:'固定情景推演',controls:[choice('task','当前需求',['输出固定 JSON','回答每天变化的库存','提示词基线仍不稳的专有客服流程','执行真实退款']),choice('method','干预方式',['提示词与结构化输出','检索实时数据（RAG）','监督微调（SFT）','工具调用与权限控制'])],goal:'选择一组匹配的需求和方法；再尝试一种不匹配的方法，比较它为什么失败。',hint:'库存是外部事实；退款是外部动作；稳定行为可以训练，但先建立提示词基线。',assumptions:'决策教学情景，不代表某方法必然达到某个真实准确率。',run:s=>{const match=s.task===s.method;const reasons=['先用 schema 和校验器约束格式；只有基线仍无法满足稳定性时，再评估微调。','实时库存应查询可信数据源。权重里的记忆会过时。','在提示词基线仍不稳定且已有足够合格示范时，SFT 可以学习稳定流程。','退款需要工具、身份权限和审批；生成“已退款”这句话不会改变账本。'];return {headline:match?'问题与干预位置匹配':'你改动的位置，未解决当前问题',metrics:[metric('本方案更新权重',s.method===2?'是':'否'),metric('需要外部事实',s.task===1?'是':'视任务而定'),metric('必须执行外部动作',s.task===3?'是':'否')],columns:['方法','改变什么','先检查'],rows:[['提示词','本次指令','格式是否可验证'],['RAG','提供给模型的资料','检索是否及时、可信'],['SFT','参数中的行为倾向','示范和隔离评测是否足够'],['工具','外部系统状态','授权、校验、回执']],findings:[reasons[s.task],match?'下一步：用未见样本验证选择，而不是用训练集证明自己。':'对照左侧四种干预位置，再试一次。'],passed:match};}},
{title:'把八条原始记录变成训练集',context:'一批真实工作形态的模拟客服记录，混有重复、个人信息和错误政策。选择清理动作，观察到底留下了什么。',mode:'公式计算',controls:[toggle('dedup','删除重复记录'),toggle('privacy','移除未脱敏隐私记录'),toggle('conflict','剔除政策矛盾'),toggle('rare','保留异常类',1)],goal:'清除三类问题，并保留两条异常类样本；对照清洗前后的数量和覆盖。',hint:'清洗不是删得越多越好。稀有但有效的异常也属于任务范围。',assumptions:'八条合成记录上的真实筛选与计数；不自动识别任意文本中的隐私或政策错误。',run:s=>{const rows=records.filter(r=>!(s.dedup&&r.flag==='重复')&&!(s.privacy&&r.flag==='隐私')&&!(s.conflict&&r.flag==='矛盾')&&(s.rare||r.intent!=='异常'));const bad=rows.filter(r=>r.flag!=='合格').length;return {headline:bad?'残留数据问题会成为训练信号':rows.some(r=>r.intent==='异常')?'清理了噪声，也保留了边界':'数据变干净，但异常场景消失了',metrics:[metric('保留记录',rows.length),metric('问题记录',bad),metric('异常场景',rows.filter(r=>r.intent==='异常').length)],columns:['ID','意图','输入','期望回答','检查'],rows:rows.map(r=>[r.id,r.intent,r.text,r.answer,r.flag]),findings:['“标注正确”指对当前政策与任务正确，不能只按表达流畅程度判断。',s.rare?'保留长尾：异常类不会因样本少而被自动删掉。':'删除异常类会让数据覆盖收窄；更多正常案例不能替代这些边界案例。'],passed:bad===0&&rows.filter(r=>r.intent==='异常').length===2};}},
{title:'问题也进模型，但哪里计分',context:'一条对话被拆成 8 个教学 token。切换损失掩码，逐个追踪哪些位置贡献训练损失。',mode:'公式计算',controls:[choice('mask','哪些位置计分',['所有位置','只计助手回答','只计用户问题']),toggle('eos','对停止标记计分',1),toggle('packing','补入 4 个 padding 位置（不拼接新对话）')],goal:'只对助手回答和停止标记计分，并确认 padding 不增加有效位置数。',hint:'输入上下文与损失掩码是两回事；用户问题仍要参与前向计算。',assumptions:'固定 token 概率下的交叉熵精确计算。为可读性手工分词；不冒充某个模型的 tokenizer。',run:s=>{const tokens=['<system>','按规则答','<user>','如何退货','<assistant>','核验订单','说明条件','<eos>'];const probabilities=[.95,.4,.97,.12,.99,.6,.35,.7];const active=tokens.map((_,i)=>i===7?!!s.eos:s.mask===0?true:s.mask===1?i>=5:i===3);const losses=probabilities.map(p=>-Math.log(p));const valid=losses.filter((_,i)=>active[i]);const rows=tokens.map((t,i)=>[t,active[i]?'计分':'仅上下文',probabilities[i],active[i]?round(losses[i],3):0]);if(s.packing)for(let i=0;i<4;i++)rows.push(['<pad>','忽略',1,0]);return {headline:'平均损失只除以有效计分位置数',metrics:[metric('有效位置',valid.length),metric('平均交叉熵',round(mean(valid),4),'自然对数，单位 nats'),metric('输入位置数',rows.length)],columns:['教学 token','掩码','目标概率','损失贡献'],rows,findings:['系统/用户内容作为上下文影响回答；不计分不代表模型没看见。','这里每行表示该目标 token 被预测时的损失；真实代码通常将 logits 与下一位置的标签错开一位。Padding 是补齐长度；packing 是把多个样本拼接，后者还需处理样本边界与注意力隔离。','停止 token 教模型何时结束。真实实现还需处理角色边界和截断。'],passed:s.mask===1&&s.eos===1&&s.packing===1};}},
{title:'随机切分为什么可能作弊',context:'6 位客户各有两条关联工单。随机按行切分可能把同一客户的近似问题同时放入训练和验证。',mode:'公式计算',controls:[choice('split','切分方式',['按行交错','按客户分组','按时间留出后两位客户']),toggle('tune','用验证结果挑过参数'),toggle('test','再保留从未参与选择的测试集')],goal:'消除客户交叉，并在调参后留出独立测试集。',hint:'分组和时间各自解决不同泄漏。调过参数的验证集已经参与了决策。',assumptions:'合成客户 ID 上真实计算集合交叉；展示结构泄漏，不生成“真实性能预测”。',run:s=>{const train=new Set<number>(),valid=new Set<number>();const rows=Array.from({length:12},(_,i)=>{const c=Math.floor(i/2);const v=s.split===0?i%2===1:s.split===1?c===1||c===4:c>=4;(v?valid:train).add(c);return [`工单 ${i+1}`,`客户 ${c+1}`,`第 ${c+1} 天`,v?'验证':'训练'];});const overlap=[...train].filter(c=>valid.has(c)).length;return {headline:overlap?'两边出现同一客户，验证可能过于乐观':'客户没有交叉，还需检查近重复内容',metrics:[metric('交叉客户数',overlap),metric('训练客户',train.size),metric('最终验收集',s.test?'另行保留':'尚未保留')],columns:['记录','客户','时间','用途'],rows,findings:['本例按客户分组时留出客户 2 和 5；按时间留出时选择最后两天的客户 5 和 6。分组测试新客户，时间留出测试较新的数据，两个问题不能互相替代。','按客户隔离能避免同一客户的近似样本泄漏，但跨客户复制文本仍需去重。',s.tune&&!s.test?'你用验证集选了参数，它不能再充当完全未见的最终验收。':'测试集应在训练、调参和挑选检查点期间保持隔离。'],passed:overlap===0&&s.tune===1&&s.test===1};}},
{title:'真的更新一个小模型',context:'模型原本认识横向特征，现在要学习纵向特征。你会实际更新两个权重和一个偏置，观察有噪声的示范怎样改变训练。',mode:'真实微型训练',controls:[slider('steps','梯度更新步数',0,0,100,5,'每次运行从相同初始权重出发，方便公平对照。'),slider('lr','学习率',.3,.05,2,.05,'决定沿梯度走多远。'),slider('noise','翻转标签的样本数',0,0,4,1,'四条目标任务样本中，有几条被错误标注。')],goal:'使用干净标签，让目标任务损失低于 0.25，并对比更新前后的概率。',hint:'先运行 0 步作为基线，再用约 60 步、学习率 0.3 训练。',assumptions:'浏览器实际执行二分类逻辑回归梯度下降；不是 Transformer，也不用于推测真实 LLM 的学习曲线。',run:s=>{const r=linearFit(s.steps,s.lr,s.noise,0);return {headline:s.noise?'模型在认真学习你给它的错误示范':'每一步都由误差推动参数更新',metrics:[metric('目标集损失',round(r.target.at(-1)!,4)),metric('训练集损失',round(r.losses.at(-1)!,4)),metric('权重',r.w.map(x=>round(x,3)).join(' / '))],columns:['目标样本','真实标签','预测正类概率'],rows:r.probabilities.map((p,i)=>[`样本 ${i+1}`,i%2===0?1:0,percent(p)]),series:[{name:'训练集损失',values:r.losses},{name:'干净目标集损失',values:r.target}],axis:'梯度步数',findings:['这两条曲线对应明确的数据；错误标签存在时，训练目标和真正想要的能力会分离。','每次运行重置初始参数；记录两次才能比较干预效果。'],passed:s.noise===0&&r.target.at(-1)!<.25};}},
{title:'全量、LoRA 和 QLoRA 放得下吗',context:'估算 7B 模型的静态参数相关显存。先拆清权重、梯度、优化器与适配器，再留下激活和临时缓冲的空间。',mode:'公式计算',controls:[choice('method','训练方式',['全量 BF16 + AdamW','LoRA + BF16 底座','QLoRA + 4-bit 底座']),slider('rank','LoRA 秩 r',16,4,64,4,'假设 32 层，每层 q/v 两个 4096×4096 矩阵。'),slider('gpu','可用显存',24,8,160,8,'这里只判断静态估算是否装得下。',' GiB'),slider('activation','激活和临时空间预算',6,2,24,2,'实际取决于序列、batch、checkpointing 和内核。',' GiB')],goal:'在 24 GiB 内找到保留 6 GiB 激活预算的可行方案，并比较另一种训练方式。',hint:'全量 AdamW 按每参数 16 字节估算；LoRA 冻结底座但仍要前向反向传播。',assumptions:'BF16 全量：权重2+梯度2+FP32主副本4+Adam状态8 字节/参数。LoRA 适配器也按16字节；4-bit底座另加15%量化元数据估算。不含分布式通信。',run:s=>{const adapter=32*2*2*4096*s.rank;const base=s.method===0?7e9*16:s.method===1?7e9*2:7e9*.5*1.15;const extra=s.method===0?0:adapter*16;const total=(base+extra)/2**30+s.activation;return {headline:total<=s.gpu?'静态预算可容纳，仍需实机测峰值':'当前静态预算已经超出显存',metrics:[metric('总估算',`${round(total,2)} GiB`),metric('训练参数量',s.method===0?'7,000 M':`${round(adapter/1e6,2)} M`),metric('剩余空间',`${round(s.gpu-total,2)} GiB`)],columns:['部分','GiB','说明'],rows:[['底座及全量状态',round(base/2**30,2),'冻结底座不保留其优化器状态'],['适配器状态',round(extra/2**30,2),'矩阵 A 与 B 的参数、梯度、优化器'],['激活与临时空间',s.activation,'人工预算，真实峰值需要测量']],findings:['LoRA 参数量：r × (输入维度 + 输出维度)，不是原矩阵参数量的固定百分比。','QLoRA 让量化底座配合可训练适配器；它不是把所有训练计算都变成 4-bit。'],passed:s.gpu===24&&s.activation>=6&&total<=24};}},
{title:'训练损失越低，检查点越好吗',context:'以下是固定的六个教学检查点。你决定何时停止，并检查有效 batch 和更新次数是否被混淆。',mode:'固定情景推演',controls:[slider('epoch','选择第几轮检查点',6,1,6,1,'数据是固定的过拟合情景。'),slider('batch','每卡 micro batch',2,1,8,1,'每次前向/反向传播处理的样本数。'),slider('accum','梯度累积次数',4,1,16,1,'累积多次后才更新一次。'),slider('gpus','GPU 数',1,1,4,1,'假设数据并行，且每卡样本数相同。')],goal:'按最低验证损失选检查点，并算出有效 batch=32 的一种配置。',hint:'第 3 轮之后，训练损失仍下降，验证损失却反弹。',assumptions:'曲线是明确给定的教学数据；batch 和更新次数按公式计算。学习率与 batch 的真实关系还取决于训练设置。',run:s=>{const train=[.9,.6,.4,.28,.18,.12],valid=[.95,.68,.55,.59,.72,.9],batch=s.batch*s.accum*s.gpus;return {headline:s.epoch===3?'你保留了验证表现最好的检查点':'训练拟合程度和泛化表现出现分歧',metrics:[metric('训练损失',train[s.epoch-1]),metric('验证损失',valid[s.epoch-1]),metric('有效 batch',batch),metric('960 条样本每轮更新次数',Math.ceil(960/batch))],columns:['轮次','训练损失','验证损失','当前选择'],rows:train.map((t,i)=>[i+1,t,valid[i],i===s.epoch-1?'选中':'']),series:[{name:'训练损失',values:train},{name:'验证损失',values:valid}],axis:'检查点（第 1–6 轮）',findings:['有效 batch = 每卡 micro batch × 梯度累积 × 数据并行卡数。','提前停止依据验证集。最终测试集不应反复参与停止或调参。'],passed:s.epoch===3&&batch===32};}},
{title:'比较回答，而不是只模仿回答',context:'一个回答更准确，另一个更长但带有虚构政策。观察 DPO 怎样使用偏好与参考模型的相对概率。',mode:'公式计算',controls:[slider('chosen','当前模型：优选回答的 log 概率',-3,-8,-1,.5,'整段回答的对数概率，教学简化。'),slider('rejected','当前模型：劣选回答的 log 概率',-3,-8,-1,.5,'同一问题下的另一段回答。'),slider('beta','β 系数',.2,.1,1,.1,'对相对间距的缩放；训练效果不能仅由这个单例推断。'),toggle('wrong','把“更长”误标成“更好”')],goal:'让真实优选的相对间距为正，且 DPO 损失低于 0.6。再对照误标偏好的后果。',hint:'参考模型的优选/劣选 log 概率固定为 −4 / −3。需要比较“差的变化”。',assumptions:'按单个偏好对计算标准 DPO logistic 损失；未执行完整模型训练。',run:s=>{const ref=-1,margin=(s.chosen-s.rejected)-ref,aligned=s.wrong?-margin:margin,z=s.beta*aligned,loss=softplus(-z);return {headline:s.wrong?'优化器会忠实放大标注中的错误偏好':'偏好信号衡量相对参考模型的变化',metrics:[metric('相对间距',round(aligned,3)),metric('偏好 logistic 值',percent(sigmoid(z)),'不是用户真实满意概率'),metric('DPO 损失',round(loss,4))],columns:['量','计算','值'],rows:[['当前间距','log π(优选) − log π(劣选)',round(s.chosen-s.rejected,2)],['参考间距','−4 − (−3)',-1],['缩放后的相对间距','β × 偏好方向 × (当前−参考)',round(z,3)]],findings:['DPO 需要可靠的偏好对和参考策略。单看优选回答概率变高并不足以理解目标。','长短、格式、语气可能成为伪偏好。评测必须检查事实、任务完成和安全边界。'],passed:!s.wrong&&margin>0&&loss<.6};}},
{title:'新业务学会了，旧任务还会吗',context:'用冲突方向的两个任务演示遗忘。目标任务推动权重往负方向移动，旧任务需要正方向；调整回放比例，看两者怎样取舍。',mode:'真实微型训练',controls:[slider('replay','每批旧样本回放数',0,0,12,1,'每批固定 4 条新任务样本；旧样本越多，目标折中越偏向旧任务。'),slider('steps','更新步数',60,0,120,10,'从原来擅长旧任务的 w=2 开始。'),slider('lr','学习率',.2,.05,.5,.05,'比较时固定学习率。')],goal:'找到新、旧任务损失都低于 0.9 的折中点；与没有回放的运行比较。',hint:'两任务在这个玩具模型里冲突。试 4 条旧样本回放，观察“保住旧任务”需要牺牲什么。',assumptions:'真实的一维逻辑回归梯度更新。刻意设置冲突标签来演示容量与目标冲突，不表示真实任务都不可兼得。',run:s=>{let w=2;const old:number[]=[],fresh:number[]=[];for(let i=0;i<=s.steps;i++){old.push(softplus(-w));fresh.push(softplus(w));if(i<s.steps)w-=s.lr*(4*sigmoid(w)+s.replay*(sigmoid(w)-1))/(4+s.replay);}return {headline:'在有限容量下，优化目标决定能力取舍',metrics:[metric('新任务损失',round(fresh.at(-1)!,4)),metric('旧任务损失',round(old.at(-1)!,4)),metric('旧样本占比',percent(s.replay/(4+s.replay)))],columns:['任务','需要的权重方向','最终损失'],rows:[['旧任务','正方向',round(old.at(-1)!,4)],['新任务','负方向',round(fresh.at(-1)!,4)]],series:[{name:'旧任务损失',values:old},{name:'新任务损失',values:fresh}],axis:'更新步数',findings:['回放改变训练分布；它能缓解遗忘，但不保证在冲突任务上两全。','真实微调还可使用较小学习率、正则化、适配器隔离，以及覆盖通用能力的回归集。'],passed:old.at(-1)!<.9&&fresh.at(-1)!<.9&&s.steps>0};}},
{title:'平均分通过，退款风险却变高了',context:'比较两个候选模型在三类客服任务上的固定评测结果。改变业务占比，观察平均分如何掩盖关键类别。',mode:'公式计算',controls:[choice('model','候选模型',['A：常见问题强','B：边界任务稳']),slider('normal','常见咨询占比',90,40,90,10,'其余比例一半退款，一半高风险异常。','%'),slider('sample','每类测试题数',50,20,200,10,'置信区间用 Wilson 95% 近似。')],goal:'让高风险异常准确率达到 80%，并检查区间下界仍有多不确定。',hint:'A 的三类准确率为 96%、78%、45%；B 为 91%、87%、84%。',assumptions:'候选模型分数为固定教学假设。按整数答对数计算加权平均与 Wilson 区间；区间只反映抽样不确定性。',run:s=>{const nominal=s.model===0?[.96,.78,.45]:[.91,.87,.84],p=nominal.map(v=>Math.round(v*s.sample)/s.sample),weights=[s.normal/100,(1-s.normal/100)/2,(1-s.normal/100)/2];return {headline:s.model===0?'平均分看起来不错，但高风险子集没有过关':'分项门槛帮助你看见平均分以外的能力',metrics:[metric('加权平均',percent(sum(p.map((v,i)=>v*weights[i])))),metric('高风险异常',percent(p[2])),metric('每类样本数',s.sample)],columns:['类别','答对 / 总数','准确率','95% 区间'],rows:p.map((v,i)=>[['常见咨询','退款','高风险异常'][i],`${Math.round(v*s.sample)} / ${s.sample}`,percent(v),wilson(Math.round(v*s.sample),s.sample).map(percent).join(' — ')]),findings:['样本占比改变报告平均分，不会改变任何一道题的实际回答。','置信区间不能修复评测污染、标签错误或部署分布变化。高风险样本还应审查错误后果。'],passed:p[2]>=.8};}},
{title:'上线是另一场实验',context:'固定一天 10,000 次请求。你安排灰度流量、比较版本与回滚阈值，计算错误预算。',mode:'公式计算',controls:[slider('canary','新版本灰度比例',10,0,100,5,'先观察小流量；灰度不是质量证明。','%'),slider('error','新版本失败率',8,0,20,1,'观测情景输入，旧版固定为 2%。','%'),slider('threshold','停止灰度阈值',5,1,15,1,'新版本失败率超过该值则回滚。','%'),toggle('compatible','适配器与底座版本匹配',1)],goal:'使用不超过 10% 的灰度，识别 8% 失败率并触发回滚，同时确保版本匹配。',hint:'监控必须能区分新旧版本。全量平均可能稀释灰度中的故障。',assumptions:'精确计算固定流量下的期望失败数；不模拟排队、采样波动和真实在线指标。',run:s=>{const volume=10000*s.canary/100,fail=volume*s.error/100+(10000-volume)*.02,rollback=s.error>s.threshold||!s.compatible;return {headline:!s.compatible?'底座与适配器不匹配，应阻止加载':rollback?'新版本触及阈值，应回滚':'继续观测，尚未触及失败率阈值',metrics:[metric('新版本请求数',volume),metric('全量期望失败数',round(fail,0)),metric('全量失败率',percent(fail/10000)),metric('新版本状态',rollback?'回滚 / 阻止':'观测中')],columns:['版本','请求数','失败率'],rows:[['旧版',10000-volume,'2%'],['新版',volume,`${s.error}%`]],findings:['小灰度中的高失败率可能被全量平均掩盖。分别按版本、任务和用户群看指标。','模型版本、底座哈希、适配器、tokenizer、模板、量化配置和评测集都应能追溯。'],passed:s.canary>0&&s.canary<=10&&s.error===8&&rollback&&s.compatible===1};}},
{title:'写一份能够被反驳的微调方案',context:'客服团队有 2,000 条已授权样本、一张 24 GiB 卡，需要稳定 JSON 与复杂退款判断。选择一套完整方案，观察缺口。',mode:'固定情景推演',controls:[toggle('baseline','先做提示词基线'),toggle('clean','清洗、脱敏并按客户隔离'),choice('method','训练方式',['全量 7B BF16 AdamW','LoRA','QLoRA']),toggle('evaluate','分项评测 + 通用能力回归'),toggle('release','保留版本并灰度回滚')],goal:'让五个验收条件全部满足，并解释为什么通过这个方案检查仍不等于模型上线达标。',hint:'考虑显存，也考虑数据隔离、基线、回归评测和可撤回的发布。',assumptions:'按公开的教学验收清单检查方案；它不预测真实训练质量，不自动批准上线。',run:s=>{const checks=[!!s.baseline,!!s.clean,s.method>0,!!s.evaluate,!!s.release];return {headline:checks.every(Boolean)?'方案闭环了，下一步用真实证据验证':'方案中仍有无法验证的假设',metrics:[metric('条件满足',`${checks.filter(Boolean).length} / 5`),metric('实际模型质量','尚未测量')],columns:['检查项','状态','要补的证据'],rows:['基线','数据与隔离','资源可行性','独立评测','发布与回滚'].map((t,i)=>[t,checks[i]?'方案已覆盖':'缺失',['同口径的提示词基线','数据来源、清洗、切分记录','实际显存峰值','质量、边界、回归置信区间','灰度指标与回滚演练'][i]]),findings:['“计划包含评测”与“评测通过”是两件事。下一阶段要实际执行和保存证据。','如果基线已经满足需求，应停在基线；是否微调由增量收益与维护成本决定。'],passed:checks.every(Boolean)};}}
];
export function initialSettings(lab:Lab):Settings {return Object.fromEntries(lab.controls.map(c=>[c.key,c.initial]));}
